### ISSUE TITLE
powershell exited with error code -196608.

### ISSUE THREAD

**Issue by Tarentaise** [AgentRev/WindowsAppsUnfukker#15]
When running it doesn't work, I get this.
```
psexec.exe -s -i powershell -ExecutionPolicy Bypass -File "WindowsAppsUnfukker.ps1"

PsExec v2.4 - Execute processes remotely
Copyright (C) 2001-2022 Mark Russinovich
Sysinternals - www.sysinternals.com


powershell exited on _Hostname_ with error code -196608.
```

**Comment by AgentRev** [comment]
You have to specify the full absolute path, e.g. "C:\Users\Tarentaise\Downloads\WindowsAppsUnfukker.ps1"

If that still doesn't work, try [PAExec](https://www.poweradmin.com/paexec/) instead of PsExec

**Comment by Tarentaise** [comment]
PAExec worked however the permissions are still broken. Fuck.

**Comment by AgentRev** [comment]
The perms from "C:\Program Files\WindowsApps", or elsewhere?

**Comment by Tarentaise** [comment]
WindowsApps, I cannot launch WindowsApps programs still. Which sucks as I cannot access Nvidia control panel.

**Comment by AgentRev** [comment]
With hidden files enabled, if you right-click WindowsApps, open Properties, and go to Security, is the SYSTEM user listed? If yes, does it have Full control?

**Comment by Tarentaise** [comment]
Reinstalling windows fixed my issue, sorry your script didn't help me though.
