### ISSUE TITLE
WARNING: AppData Packages not found

### ISSUE THREAD

**Issue by abasgames** [AgentRev/WindowsAppsUnfukker#17]
Backup of existing permissions...
Successfully processed 0 files; Failed processing 0 files
Saved to C:\Program Files\WindowsApps_20230208_212519.txt

Fixing WindowsApps permissions...

Fixing WindowsApps subfolders inheritance...
Successfully processed 233 files; Failed processing 0 files

Fixing WindowsApps subfolders permissions...
Fixing C:\Program Files\WindowsApps\Microsoft.Advertising.Xaml_10.1808.3.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.DirectXRuntime_9.29.1974.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.DirectXRuntime_9.29.1974.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.Getstarted_10.2210.3.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.HEIFImageExtension_1.0.43012.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.LanguageExperiencePackar-SA_19041.42.130.0_neutral__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.LanguageExperiencePackar-SA_19041.43.138.0_neutral__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.MinecraftUWP_1.19.6003.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.1.7_1.7.25531.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.1.7_1.7.27413.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.1.7_1.7.27413.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.0_2.0.27427.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.0_2.0.27427.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.27405.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.1.7_1.7.25531.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.1.7_1.7.27422.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.1.7_1.7.27422.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.0_2.0.25709.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.0_2.0.25709.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.2_2.2.27328.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.0_2.1810.18004.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.0_2.1810.18004.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.3_2.32002.13001.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.3_2.32002.13001.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.4_2.42007.9001.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.4_2.42007.9001.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.5_2.52012.2002.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.5_2.52012.2002.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.6_2.62112.3002.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.6_2.62112.3002.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.7_7.2208.15002.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.7_7.2208.15002.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.8_8.2212.15002.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.8_8.2212.15002.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.110.00.UWPDesktop_11.0.61135.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.110.00.UWPDesktop_11.0.61135.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.120.00.UWPDesktop_12.0.40653.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.120.00.UWPDesktop_12.0.40653.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.30704.0_x86__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.VP9VideoExtensions_1.0.52781.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Microsoft.WebpImageExtension_1.0.52351.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Resources\Microsoft.4297127D64EC6_1.1.28.0_x64__8wekyb3d8bbwe
Fixing C:\Program Files\WindowsApps\Resources\Microsoft.MinecraftJavaEdition_1.0.5.0_x64__8wekyb3d8bbwe

WARNING: AppData Packages not found, please file a GitHub issue here:
https://github.com/AgentRev/WindowsAppsUnfukker/issues
Copy-paste this in the description: C:\Users\mustafa\AppData\Local\Packages

**Comment by AgentRev** [comment]
Looks fine, shouldn't be a problem. Did the script solve your issue?

**Comment by abasgames** [comment]
Yes it did
