### ISSUE TITLE
Successfully processed but still "Paramater Incorrect Error"

### ISSUE THREAD

**Issue by 5l1v3r1** [AgentRev/WindowsAppsUnfukker#21]
Since psexec is not working for me i did it with nirsofts nircmd tool (actually advancedrun does the same to run as system admin). And the result is :

"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File "C:\Users\kali\Desktop\son\WindowsAppsUnfukker.ps1"

Welcome to the amazing WindowsApps Unfukker! Please sit tight!!

Backup of existing permissions...
Successfully processed 0 files; Failed processing 0 files
Saved to C:\Program Files\WindowsApps_20230519_190806.txt

Fixing WindowsApps permissions...

Fixing WindowsApps subfolders inheritance...
Successfully processed 164 files; Failed processing 0 files

Fixing WindowsApps subfolders permissions...
Fixing C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe

Fixing AppData Packages permissions, this could take a couple minutes...
Successfully processed 7196 files; Failed processing 0 files
processed file: C:\Users\kali\AppData\Local\Packages
Successfully processed 1 files; Failed processing 0 files

Unfukking finished!! (hopefully)"

Why do i still get the paramater inccorrect error when i try to run windows store apps?

Can you please help me with that. I just reverted back to windows 10 from windows 11 and thought it was related to windows 11. But now windows 10 has the same error.

**Comment by 5l1v3r1** [comment]
Tried again with paexec and the result is the same. It says successful but  Still having the "Incorrect Parameter" with most of the Windows Store Apps like terminal, nvidia etc.. When i checked my second pc for the permissions. I realized the apps folder itself is owned by TrustedInstaller as expected but the subfolders like terminals etc belong the system. But with this scripts everything becomes owned by TrustedInstaller. Secondly I realized if i run the WindowsApps with the administrations rights they run flawlessly but as normally they always give the error of "Incorrect Parameter" and also other programs also get effected slightly like winrar and iobit uninstaller etc.. They give different errors. I did not mess up witht the ownerships. It just happened while i was on my routine work on windows. What do you think it could be? I am sick and tired of this shitty windows but most of the programs i use for the work only runs on windows.

**Comment by AgentRev** [comment]
The script does not alter the ownership of subfolders under WindowsApps. All my subfolders remain owned by `SYSTEM` after running the script. Can you zip and send me your earliest `C:\Program Files\WindowsApps_XXX.txt` backup?

**Comment by 5l1v3r1** [comment]
Alright. Here you go https://www.upload.ee/files/15249047/WindowsApps_20230519_185656.zip.html. I also tried copying for example terminal folder to desktop and guess what from that folder i tried to run terminal and again it just works flawlessly. Somehow windowsapps folder is messed up and neither your script nor any solutions online have helped me so far. I don't know this happened at windows 11 for me as well and that was the reason i moved back to windows 10. Again same shit happening. I literally hate windows. It is a piece of licenced malware by the biggest scam called microsoft. Microsoft just dumbs down our computers and limits their capabilities but yet money hungry companies and game producers etc still preparing their softwares just on windows. I will donate linux foundation and i also make friends donate them. That's the only thing i can do.

**Comment by 5l1v3r1** [comment]
Secondly i also realized since nvidia control center is not working due to that parameter error , i tried to reinstall it and it does not even let me install the new geforce experience or directly the driver itself. I think something really messed up with group policy or user permissions. I don't wanna format and reinstall everything from the beginning. I tried every possible solution online nothing has worked so far. And i got the results for virus scanner now. Some nasty virus or malware there is and let me clear them first. That's why i hate windows, every malware is created for this shitty operating system. On macos or on linux you don't even need to install antivirus solutions. (yes there are malwares for them but mostly very sophisticated and target vips etc not us)

**Comment by AgentRev** [comment]
I looked at your backup but I don't see anything that stands out. Your problem could be beyond the capabilities of my script. As for Nvidia drivers, maybe you could try this: https://linustechtips.com/topic/1419160-windowsapps-folder-access-denied/#comment-15599650

**Comment by AgentRev** [comment]
Alright, good luck!
