### ISSUE TITLE
script cannot run

### ISSUE THREAD

**Issue by Meonthb** [AgentRev/WindowsAppsUnfukker#24]
when I run this script, prompts those information:

C:\Users\login\Downloads\PSTools>psexec.exe -s -i powershell -ExecutionPolicy Bypass -File "FULL_PATH_HERE\WindowsAppsUnfukker.ps1"

PsExec v2.43 - Execute processes remotely
Copyright (C) 2001-2023 Mark Russinovich
Sysinternals - www.sysinternals.com

powershell exited on AVALON with error code -196608.

How can I fix it?

**Comment by AgentRev** [comment]
You need to replace `FULL_PATH_HERE` with the actual file path

**Comment by Meonthb** [comment]
Thank you so much, now it seems everything is running OK!
