### ISSUE TITLE
Minor Issue - Rest everything works well!

### ISSUE THREAD

**Issue by K3n20** [AgentRev/WindowsAppsUnfukker#27]
First of all super thanks for making this awesome script! It works well!! after searching the internet and trying half working solutions, I came across your script, and it fixed my issue! Many thanks!

The script has an out of context "else" block at line 232 which fails its execution. I locally made the change, shifted the "else" block inside the previous "elseif", to be precise i placed it after line 228 (you know what i mean!). The script ran well after that and my system is back to normal!

Once again super thanks for this awesome fix and please fix this minor error in the script. Cheers!

**Note:** I had moved the else block in the said position as it appeared to be the right place, if not please do move it in the right position as per your logic flow!

Before:

![image](https://github.com/AgentRev/WindowsAppsUnfukker/assets/62912138/1e6d8cf7-7257-4b0d-a9cc-2883d24383c9)

After:

![image](https://github.com/AgentRev/WindowsAppsUnfukker/assets/62912138/3416aadf-ce19-4042-a460-a5102526f918)

**Comment by AgentRev** [comment]
https://github.com/AgentRev/WindowsAppsUnfukker/commit/e541fec4e6f3d7e407f1aaa07ef64f62d090b64a
