### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by Wraith0530** [AgentRev/WindowsAppsUnfukker#34]
Nevermind your boy was being stupid due to stress of botching his legion go lol
this is my issue 
paexec -s -i powershell -ExecutionPolicy Bypass -File C:\Users\wrait\Downloads\WindowsAppsUnfukker.ps1" "%LocalAppData%" 
with a response that looks like this
PAExec v1.29 - Execute Programs Remotely
Copyright (c) 2012-2021 Power Admin LLC
www.poweradmin.com/PAExec

Connecting to {local server}...
Failed to impersonate [] - continuing anyway. The handle is invalid. [Err=0x6, 6]
Starting PAExec service on {local server}...

powershell returned -196608

PAExec returning exit code -196608

What do I need to do?

**Comment by AgentRev** [comment]
The answer is in the readme:
> If it says exit code -196608, it means the path is invalid, double-check the `-File` path you entered

**Comment by Wraith0530** [comment]
Thank you for the response! I had been battling with it for about an hour and decided to just take out the end of your mock path and use the whole thing. I appreciate you, sorry for the incompetence, trying to save my legion go from microsoft being dumb.
