### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by pctweakers1** [AgentRev/WindowsAppsUnfukker#6]
Confirmed - Worked like a dream for me first try - yes he is a god heh...

**Comment by franzbischoff** [comment]
I'm about to run this script after hours of desperation and google search.
I hope you are the man that will save me.

**Comment by pctweakers1** [comment]
What is the issue, this saved me a lot of headaches when nothing else would
even scratch the surface. Do you have discord?

**Comment by pctweakers1** [comment]
Or hell man call me +1(918)882-5237

**Comment by franzbischoff** [comment]
discord would be good, I'm in Europe ! :-D

**Comment by anthonycastaneda** [comment]
> I'm about to run this script after hours of desperation and google search.
> I hope you are the man that will save me.

The script is a godsend.

**Comment by franzbischoff** [comment]
It is working! btw, I had problems with psexec, and I'm running with paexec

**Comment by franzbischoff** [comment]
![image](https://user-images.githubusercontent.com/984592/202818967-2eb14a0a-d15d-4811-88c8-bf496e03634d.png)

**Comment by franzbischoff** [comment]
MAAAAAAAAAAAAAAAAAAAAAAAAAAN!!!! I have my stuff back! you are awesome!

**Comment by franzbischoff** [comment]
Where is the patreon link? you will be rich!

**Comment by pctweakers1** [comment]
https://discord.gg/qXVNzhXF

**Comment by AgentRev** [comment]
> Where is the patreon link? you will be rich!

I don't accept donations, enjoy your peace of mind.

**Comment by Saud-97** [comment]
You saved another lost soul. You should accept donations I mean how can we thank you.


> I don't accept donations, enjoy your peace of mind.
